# Generated by Django 2.1.7 on 2020-04-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravite', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Eleve', 'Eleve')], max_length=50, verbose_name='Gravite-Ticket')),
                ('etat', models.CharField(max_length=50, verbose_name='Etat-Ticket')),
                ('delai', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateAssignation', models.DateTimeField(default=django.utils.timezone.now)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titre')),
                ('version', models.CharField(max_length=10, verbose_name='Titre')),
                ('description', models.CharField(max_length=300, verbose_name='Titre')),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('dateOuverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('solution', models.CharField(max_length=5000, verbose_name='Description')),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravite', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Eleve', 'Eleve')], max_length=50, verbose_name='Gravite-Ticket')),
                ('etat', models.CharField(max_length=50, verbose_name='Etat-Ticket')),
                ('delai', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateAssignation', models.DateTimeField(default=django.utils.timezone.now)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titre')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titre')),
                ('version', models.CharField(max_length=10, verbose_name='Titre')),
                ('description', models.CharField(max_length=300, verbose_name='Titre')),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('dateOuverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('solution', models.CharField(max_length=5000, verbose_name='Solution')),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestionnaire.Produit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('name', 'version', 'dateCreation')},
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('name', 'data', 'date', 'description')},
        ),
        migrations.AddField(
            model_name='assignation',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestionnaire.Ticket'),
        ),
        migrations.AddField(
            model_name='archiveticket',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestionnaire.Produit'),
        ),
        migrations.AlterUniqueTogether(
            name='archiveproduit',
            unique_together={('name', 'version', 'description', 'dateCreation')},
        ),
        migrations.AddField(
            model_name='archiveassignation',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestionnaire.Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('titre', 'produit', 'initiateur', 'dateOuverture', 'description', 'solution')},
        ),
        migrations.AlterUniqueTogether(
            name='assignation',
            unique_together={('ticket', 'support', 'gravite', 'etat', 'delai', 'dateAssignation')},
        ),
        migrations.AlterUniqueTogether(
            name='archiveticket',
            unique_together={('titre', 'produit', 'initiateur', 'dateOuverture', 'description', 'solution')},
        ),
        migrations.AlterUniqueTogether(
            name='archiveassignation',
            unique_together={('ticket', 'support', 'gravite', 'etat', 'delai', 'dateAssignation')},
        ),
    ]
