# Generated by Django 2.1.7 on 2020-04-30 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestionnaire', '0003_auto_20200430_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='archiveticket',
            unique_together={('titre', 'produit', 'initiateur', 'description', 'solution')},
        ),
        migrations.AlterUniqueTogether(
            name='assignation',
            unique_together={('categorie', 'ticket', 'support', 'gravite', 'etat', 'delai')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('titre', 'produit', 'initiateur', 'description', 'solution')},
        ),
    ]
