# Generated by Django 2.1.7 on 2020-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire', '0005_auto_20200430_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('name',)},
        ),
    ]
