# Generated by Django 2.1.7 on 2020-04-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire', '0006_auto_20200430_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('name', 'version')},
        ),
    ]
